create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;


postgres://
lvdncfrpgknnvq
:
2a49e5c2fc417da086e4c8b0de0627a92fe24adb2ad45c1e28956e80468cde24
@
ec2-35-174-35-242.compute-1.amazonaws.com
:
5432
/
d28h1eh4cpg9rh



